### ISSUE TITLE
Extracting Pose

### ISSUE THREAD

**Issue by nfprojets** [salykovaa/inerf#10]
Hi, I just curious what the dummy pose actually is? Is it the the pose (camera-to-world) of rendered image? I tried to save the dummy pose and I found if the first frame always return the 4x4 homogeneous matrix but the rest frames are 3x4 homogeneous. Since I'm a newbie in a NeRF stuff I hope you can enlighten me for this! Thanks!

https://github.com/salykovaa/inerf/blob/00cb8ff0b279d3dc102a7939f1bbf7c7ff005f0e/run.py#L185

**Comment by salykova** [comment]
Hi @greennpatrick 

`dummy_pose` is just both a cpu and numpy copy of `pose`. The `pose` is on gpu, so we need to copy it and transfer to cpu in order to do calculations. `dummy_pose` is then used to calculate rotation and translation error between estimated and ground truth pose
