### ISSUE TITLE
how can I get the transforms.json

### ISSUE THREAD

**Issue by USTBVEO** [salykovaa/inerf#11]
Hi author. Thanks for your great work!
I want to ask how can I get the transforms.json when I test my own nerf model and data trained in nerf-pytorch ( which you mentioned in Readme.md)
I have trained my nerf model. When I want to test in inerf, it comes that I don't know how to generate the json file just like lego or chair you provided in your program.
![image](https://user-images.githubusercontent.com/50726335/229262872-690a1d6d-1ad3-46e1-bb01-a576d9a3808e.png)
![image](https://user-images.githubusercontent.com/50726335/229262902-650df9df-9b63-4bbc-bebd-3bc45f68c0c6.png)

**Comment by salykova** [comment]
Hi @USTBVEO 

You can use for example the script from here [https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md](https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md) 

[colmap2nerf.py](https://github.com/NVlabs/instant-ngp/blob/master/scripts/colmap2nerf.py)
