### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by cugwzl** [salykovaa/inerf#3]
The initial poses（start_pose）in the code seem to have been calculated from GroundTruth,I don't know if I'm getting this wrong.If it's based on the calculation, isn't it inappropriate.
I would appreciate it if you could kindly reply to me in your spare time.

**Comment by salykova** [comment]
Hi,

start_pose is calculated from GroundTruth in order to test influence of initial error. However, initial pose of cam_transf is chosen randomly [see here](https://github.com/salykovaa/inerf/blob/00cb8ff0b279d3dc102a7939f1bbf7c7ff005f0e/inerf_helpers.py#L21).
