### ISSUE TITLE
Requirements probelm(resolved)

### ISSUE THREAD

**Issue by StarsTesla** [salykovaa/inerf#4]
I followed the requirements install opencv-python 4.2, the erro shows:

`Traceback (most recent call last):
  File "run.py", line 221, in <module>
    run()
  File "run.py", line 87, in run
    POI = find_POI(obs_img_noised, DEBUG)  # xy pixel coordinates of points of interest (N x 2)
  File "B:\code\inerf\utils.py", line 184, in find_POI
    sift = cv2.SIFT_create()
AttributeError: module 'cv2.cv2' has no attribute 'SIFT_create'`

then I tired 4.1 and 4.5, changed the opencv-python opencv-contrib-python opencv-python-headless to 4.5.5.64, problem solved.

**Comment by salykova** [comment]
Thanks for the information! I have already updated requirements.txt
