### ISSUE TITLE
Question about the code of  "camera_transf" 

### ISSUE THREAD

**Issue by LZL-CS** [salykovaa/inerf#5]
Hi,

Thanks for your work in implementing the work of iNeRF.
May I know how to understand lines 29 and 30 of the code, and is there a formula I can refer to?

https://github.com/salykovaa/inerf/blob/00cb8ff0b279d3dc102a7939f1bbf7c7ff005f0e/inerf_helpers.py#L29
https://github.com/salykovaa/inerf/blob/00cb8ff0b279d3dc102a7939f1bbf7c7ff005f0e/inerf_helpers.py#L30

**Comment by salykova** [comment]
Hi! I took this formula from the book [Modern Robotics](http://hades.mech.northwestern.edu/images/7/7f/MR.pdf) page 105. It is a transformation matrix in "exponential" coordinates. 

Here is also a good source: [Twists and Exponential Coordinates](https://danieltakeshi.github.io/2018/01/11/twists-and-exponential-coordinates/)

**Comment by LZL-CS** [comment]
> Hi! I took this formula from the book [Modern Robotics](http://hades.mech.northwestern.edu/images/7/7f/MR.pdf) page 105. It is a transformation matrix in "exponential" coordinates.
> 
> Here is also a good source: [Twists and Exponential Coordinates](https://danieltakeshi.github.io/2018/01/11/twists-and-exponential-coordinates/)

Hi, thanks for your reply. I'll have a look of this formula.
