### ISSUE TITLE
inerf accuracy

### ISSUE THREAD

**Issue by jianglh-WHU** [salykovaa/inerf#6]
Thanks for your excellent work!
After reading your code, I find your start_pose has a 10 degree rotation for the z-axis.
So could I know whether your code able to recover pose within 40 degrees of rotation, as mentioned in the paper? In other words, what is the approximate accuracy of your code's maximum recovery of rotation and translation?

hope for your reply!

**Comment by jianglh-WHU** [comment]
Oh,after some experiments, for lego scenes
a maximum of 60 degrees of rotation or 0.8 t or 0.5 brightness can be recovered

**Comment by salykova** [comment]
Hi! 10 degree initial rotation was chosen randomly (just as an example 😅)

 It depends on scenes (real data, or synthetic) and on particular axis. Average initial rotational error, which I was able to recover was approximately 40 degree. I didn't test translation.
