### ISSUE TITLE
How can I get the ckpts of trained weights for my own dataset?

### ISSUE THREAD

**Issue by LZL-CS** [salykovaa/inerf#8]
Hi, thanks for your work. May I know how can I get the trained weights for iNeRF for new scenes(my own dataset)? Do I need to first train my dataset using the pixelNeRF? Hope for your reply, thanks!

**Comment by salykova** [comment]
Hi!

This implementation works only with original NeRF and not with pixelNeRF. Models were trained with pytorch implementation of NeRF. See Readme. That is, for each new scene, the NeRF model must be trained from scratch.
