### ISSUE TITLE
Lie algebra problem

### ISSUE THREAD

**Issue by BoMingZhao** [salykovaa/inerf#9]
Thank you for your excellent work! 

During my running process, I found that optimizing the pose does not necessarily satisfy the Lie algebra. What could be the reason for this?

![1677849261660](https://user-images.githubusercontent.com/26064261/222729123-20329911-1eda-4c3a-805d-a78e9da771a8.png)

**Comment by salykova** [comment]
Hi @BoMingZhao,

May I ask you, what do you mean exactly by "doesn't satisfy the Lie algebra"?

**Comment by BoMingZhao** [comment]
> Hi @BoMingZhao,
> 
> May I ask you, what do you mean by "doesn't satisfy the Lie algebra" exactly?

What I mean is that for a 3x3 rotation matrix, it’s transpose should be equal to it's inverse matrix. However, I found that R.T and R.inverse are not equal later on.

**Comment by flybiubiu** [comment]
same problem

**Comment by salykova** [comment]
Hi @flybiubiu  @BoMingZhao 

Since the error is small, I assume that it is a numerical noise
